Service Agent watches Service Classes' resources
primaza/primaza pull request #120
Opened 2023-04-19 07:50 UTC by Kartikey-star

2023-04-24 09:49 UTC, filariow requested changes
some nits

2023-04-24 09:49 UTC, filariow commented on test/acceptance/features/steps/kubernetesapi.py
> +            name=name),
this can be refactored after #126 got merged. Also applies below.

2023-04-24 09:49 UTC, filariow commented on docs/architecture/agents.md
> +Service agents are installed into Cluster Enviuronment's service namespaces.
```suggestion
Service agents are installed into Cluster Environment's service namespaces.
```

2023-04-24 09:49 UTC, filariow commented on docs/architecture/agents.md
> +The informer monitors changes to resources matching the Service Class specifications and updates the  Registered Services on Primaza control plane.
```suggestion
The informer monitors changes to resources matching the Service Class specifications and updates the Registered Services on Primaza control plane.
```

2023-04-24 09:49 UTC, filariow commented on test/acceptance/features/serviceClassWatch.feature
> +        """
can this be moved to `Background` too?

2023-04-24 09:49 UTC, filariow commented on test/acceptance/features/steps/kubernetesapi.py
> +            name=name),
as #126 got merged this can be refactored. Also applies at the method below.

2023-04-24 09:49 UTC, filariow commented on controllers/agents/svc/serviceclass_controller.go
> +	if err = r.Informer(ctx, mapping.Resource, serviceClass); err != nil {
```suggestion
	if err = r.RunInformer(ctx, mapping.Resource, serviceClass); err != nil {
```

2023-04-24 09:49 UTC, filariow commented on controllers/agents/svc/serviceclass_controller.go
> +			Namespace: "primaza-system",
add a `// TODO` here, as we need eventually to make it dynamic.

2023-04-24 12:47 UTC, Kartikey-star commented on test/acceptance/features/steps/kubernetesapi.py
> +        check_success=lambda x: x is not None,
Yeah , i missed that

2023-04-24 21:48 UTC, sadlerap reviewed
Q: how are we removing the informer when the service class gets deleted?  I'm not quite sure how this current approach is accomplishing that, and I'd prefer not to have stale watches lying around.

2023-04-25 10:02 UTC, Kartikey-star commented
> Q: how are we removing the informer when the service class gets deleted? I'm not quite sure how this current approach is accomplishing that, and I'd prefer not to have stale watches lying around.

@sadlerap that is a good catch. Thanks. Have added code to signal the informers to stop and also delete the  informer key's from the map.

2023-04-26 13:46 UTC, filariow approved these changes
lgtm

2023-04-26 13:47 UTC, merged