Service Catalog Documentation
primaza/primaza pull request #98
Opened 2023-04-03 11:09 UTC by Kartikey-star

2023-04-03 16:55 UTC, dperaza4dustbit reviewed
Looks good, just one comment to fix

2023-04-03 16:55 UTC, dperaza4dustbit commented on docs/entities/servicecatalog.md
> +A Service Claim represents a group of Registered Services which are available in a Cluster Environment.
Catalog not Claim

2023-04-04 09:09 UTC, filariow requested changes
a few nits

2023-04-04 09:09 UTC, filariow commented on docs/entities/servicecatalog.md
> +contains a list of `ServiceCatalogService`. The Service Catalog Service contains the following fields:
For a better review experience please format the markdown as follow. Oneline for each sentence, one empty line for creating a new paragraph.

```suggestion
The definition of a ServiceCatalog can be obtained directly from our [ServiceCatalog CRD](../../config/crd/bases/primaza.io_servicecatalogs.yaml).
The specification contains a list of `ServiceCatalogService`.
The Service Catalog Service contains the following fields:
```

2023-04-04 13:21 UTC, dperaza4dustbit approved these changes
lgtm

2023-04-04 13:26 UTC, merged